#!/bin/bash

yum install -y gcc
cd /tmp
wget -O ta-lib-0.4.0-src.tar.gz http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar xvzf ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix=/usr
make & make install

easy_install pip
cd /home/ec2-user/daikokuten
pip install -r requirements.txt

chkconfig --add daikokuten
chkconfig daikokuten on